In [1]:
import tensorflow as tf

# Learn Tensorflow

### What is a Tensorflow session

The following notes come from [this blog](http://danijar.com/what-is-a-tensorflow-session/)

Graph defines the computation, session execute graphs (or part of graph)

In [3]:
# define graph
variable = tf.Variable(42, name='foo')
initialize = tf.global_variables_initializer()
assign = variable.assign(13)

In [5]:
# run graph in session
with tf.Session() as sess:
    sess.run(initialize)
    sess.run(assign)
    print(sess.run(variable))

13


### Constant Types

The following notes come from Stanford CS20si

In [15]:
a = tf.constant([2, 2], name='vector') # specify name (1d tensor)
b = tf.constant([[0, 1], [2, 3]]) # 2*2 matrix 
c = tf.zeros([2, 3], tf.int32) # specify data type
d = tf.zeros_like(b) # same shape
e = tf.fill([2, 3], 8) # fill with same value
with tf.Session() as sess:
    print('a:')
    print(sess.run(a))
    print('b:')
    print(sess.run(b))
    print('c:')
    print(sess.run(c))
    print('d:')
    print(sess.run(d))
    print('e:')
    print(sess.run(e))

a:
[2 2]
b:
[[0 1]
 [2 3]]
c:
[[0 0 0]
 [0 0 0]]
d:
[[0 0]
 [0 0]]
e:
[[8 8 8]
 [8 8 8]]


In [20]:
f = tf.linspace(10.0, 13.0, 4) # lin seq
g = tf.range(10.0, 14.0, 1) # lin seq, another way
# PA: they are not iterable

In [21]:
with tf.Session() as sess:
    print('f:')
    print(sess.run(f))
    print('g:')
    print(sess.run(g))

f:
[ 10.  11.  12.  13.]
g:
[ 10.  11.  12.  13.]


In [27]:
h = tf.random_normal([2, 2]) # random normal
i = tf.truncated_normal([2, 2]) # truncated normal
j = tf.random_uniform([2, 2])
k = tf.random_shuffle(b) # randomly shuffle tensor along 1st dimension
l = tf.random_crop(b, [2, 1])

In [28]:
with tf.Session() as sess:
    print('h:')
    print(sess.run(h))
    print('i:')
    print(sess.run(i))
    print('j:')
    print(sess.run(j))
    print('k:')
    print(sess.run(k))
    print('l:')
    print(sess.run(l))

h:
[[ 0.85499239 -2.04008007]
 [-1.58856726 -0.66515911]]
i:
[[-0.74781948 -0.619923  ]
 [ 0.37858662  1.35265982]]
j:
[[ 0.74662387  0.18286121]
 [ 0.38211346  0.03005338]]
k:
[[2 3]
 [0 1]]
l:
[[0]
 [2]]


### Math Operations

In [31]:
with tf.Session() as sess:
    print('a:')
    print(sess.run(a))
    print('b:')
    print(sess.run(b))

a:
[2 2]
b:
[[0 1]
 [2 3]]


In [38]:
with tf.Session() as sess:
    print('add:')
    print(sess.run(tf.add(a, b))) # elementwise add
    print('add_n:')
    print(sess.run(tf.add_n([b, b, b]))) # b+b+b

add:
[[2 3]
 [4 5]]
add_n:
[[0 3]
 [6 9]]


In [42]:
with tf.Session() as sess:
    print('mul:')
    print(sess.run(tf.multiply(a, b))) # elementwise mul
    print('matmul')
    print(sess.run(tf.matmul(tf.reshape(a, shape=[1,2]), b))) # b+b+b

mul:
[[0 2]
 [4 6]]
matmul
[[4 8]]


In [44]:
with tf.Session() as sess:
    print('div:')
    print(sess.run(tf.div(b, a)))
    print('mod')
    print(sess.run(tf.mod(b, a))) # b+b+b

div:
[[0 0]
 [1 1]]
mod
[[0 1]
 [0 1]]


### Variables