# Variables and Operations

In [1]:
import tensorflow as tf
import numpy as np

### Constant Tensors

In [9]:
x_1 = tf.constant([1,2,3])
x_2 = tf.constant(np.array([2,3,4]), dtype=tf.float32)
x_3 = tf.zeros([3,2], dtype=tf.float32)
x_4 = tf.zeros_like(x_1)
x_5 = tf.ones([3,2], dtype=tf.int32)

with tf.Session() as s:
    ans_1 = s.run(x_1)
    ans_2 = s.run(x_2)
    ans_3 = s.run(x_3)
    ans_4 = s.run(x_4)
    ans_5 = s.run(x_5)

In [10]:
ans_1

array([1, 2, 3], dtype=int32)

In [11]:
ans_2

array([ 2.,  3.,  4.], dtype=float32)

In [12]:
ans_3

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]], dtype=float32)

In [13]:
ans_4

array([0, 0, 0], dtype=int32)

In [14]:
ans_5

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

### Basic Operations

#### Arithmetic Operators

In [18]:
with tf.Session() as s:
    print('operator +:')
    print(s.run(tf.cast(x_1, tf.float32) + x_2))

operator +:
[ 3.  5.  7.]


In [20]:
with tf.Session() as s:
    print('tf add:')
    print(s.run(tf.add(x_1, tf.cast(x_2, tf.int32))))

tf add:
[3 5 7]


In [22]:
with tf.Session() as s:
    print('tf mul:')
    print(s.run(tf.multiply(x_1, tf.cast(x_2, tf.int32))))

tf mul:
[ 2  6 12]


In [24]:
x_6 = tf.constant([[1,2],[3,4],[5,6]], dtype=tf.float32)
with tf.Session() as s:
    print('tf matmul:')
    print(s.run(tf.matmul(x_2, x_6)))

tf matmul:


TypeError: Input 'b' of 'MatMul' Op has type int32 that does not match type float32 of argument 'a'.

#### Other [Basic Math Functions](https://www.tensorflow.org/versions/r0.10/api_docs/python/math_ops/basic_math_functions)