# Numpy
Numpy tutorial can be found at [here](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html).

## Basics
### Initialize ndarray

In [2]:
import numpy as np
a = np.zeros((2,2))
b = np.eye(2)                # only one number is needed here
c = np.ones((2,2), dtype=np.int16)
d = np.full((2,2),7, dtype=np.int64)
e = np.random.random((2,2))
f = np.array([1,2,3])
print 'a='+str(a)
print 'b='+str(b)
print 'c='+str(c)
print 'd='+str(d)
print 'e='+str(e)
print 'f='+str(f)

a=[[ 0.  0.]
 [ 0.  0.]]
b=[[ 1.  0.]
 [ 0.  1.]]
c=[[1 1]
 [1 1]]
d=[[7 7]
 [7 7]]
e=[[ 0.73636178  0.40140511]
 [ 0.04103401  0.75093747]]
f=[1 2 3]


### ndarray attributes

In [5]:
print 'dimension of a='+str(a.ndim)
print 'shape of b='+str(b.shape)
print 'size of c='+str(c.size)       # total number of elements
print 'dtype of d='+str(d.dtype)

dimension of a=2
shape of b=(2, 2)
size of c=4
dtype of d=int64


### Create sequence of numbers

In [6]:
print np.arange(10, 30, 5)           # start, end(exclusive), step
print np.linspace(10, 25, 4)         # start, end, #elements, get exact number as we want

[10 15 20 25]
[ 10.  15.  20.  25.]


In [8]:
a = np.array([[1,2,3],[4,5,6]])
print a
print a.reshape((3,2))               # reshape the array, '(' and ')' are needed

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


## operations
In numpy, \* operates **elementwise**. Use 'np.dot' for matrix product

In [9]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[6,5,4],[3,2,1]])
print a*b                           # element product

[[ 6 10 12]
 [12 10  6]]


In [10]:
print np.dot(a,np.transpose(b))     # matrix product

[[28 10]
 [73 28]]


sum, min, max are methods of ndarray class

In [11]:
a = np.random.random((2,3))
print a

[[ 0.48223425  0.33671189  0.15391381]
 [ 0.25623811  0.17841378  0.67016424]]


In [12]:
print a.sum(axis=0)                 # column sum
print a.sum(axis=1)                 # row sum

[ 0.73847236  0.51512567  0.82407806]
[ 0.97285996  1.10481613]


In [14]:
print a.max(axis=0)
print a.max(axis=1)

[ 0.48223425  0.33671189  0.67016424]
[ 0.48223425  0.67016424]


In [15]:
print a.min(axis=0)
print a.min(axis=1)

[ 0.25623811  0.17841378  0.15391381]
[ 0.15391381  0.17841378]


NumPy provides familiar mathematical functions such as _sin_, _cos_, and _exp_. In NumPy, these are called “**universal functions**”(ufunc). Within NumPy, these functions operate **elementwise** on an array, producing an array as output.

In [50]:
b = a.reshape((1,-1))               # -1 can be set as default number
print b

[[ 0.34824388  0.73915642  0.76012123  0.963917    0.57135937  0.41584273]]


In [20]:
print np.exp(b)
print np.sqrt(b)
print np.sin(b)

[[ 1.61968916  1.40033555  1.16639036  1.29206034  1.19531982  1.95455831]]
[[ 0.69443089  0.58026881  0.39231851  0.50619967  0.42239056  0.8186356 ]]
[[ 0.46375979  0.33038541  0.15330684  0.25344329  0.17746876  0.62111471]]


Several arrays can be stacked together along different axes

In [56]:
a = np.random.random((3, 2))
b = np.random.random((3, 2))
print a
print b

[[ 0.76651711  0.17434956]
 [ 0.33796489  0.16795555]
 [ 0.66589005  0.55650589]]
[[ 0.6126561   0.09976938]
 [ 0.18493268  0.20998451]
 [ 0.65490457  0.03959721]]


In [57]:
print np.vstack((a, b))           # vertical stack
print np.hstack((a, b))           # horizontal stack

[[ 0.76651711  0.17434956]
 [ 0.33796489  0.16795555]
 [ 0.66589005  0.55650589]
 [ 0.6126561   0.09976938]
 [ 0.18493268  0.20998451]
 [ 0.65490457  0.03959721]]
[[ 0.76651711  0.17434956  0.6126561   0.09976938]
 [ 0.33796489  0.16795555  0.18493268  0.20998451]
 [ 0.66589005  0.55650589  0.65490457  0.03959721]]


## Indexing, Slicing and Iterating
Operation for one-dimension _ndarry_ is similar to _list_ in python

In [22]:
a = np.random.random(5)
print a

[ 0.50712513  0.01798379  0.09065167  0.20181364  0.83580155]


In [28]:
print a[1:3]                 # second and third (second argument is exclusive)
print a[:3]                  # first to third
print a[-1]                  # last
print a[:-1]                 # first to second last
print a[0:5:2]               # every second element

[ 0.01798379  0.09065167]
[ 0.50712513  0.01798379  0.09065167]
0.835801546492
[ 0.50712513  0.01798379  0.09065167  0.20181364]
[ 0.50712513  0.09065167  0.83580155]


In [29]:
for elem in a:
    print elem

0.507125127938
0.017983790128
0.0906516708985
0.201813644801
0.835801546492


Multidimensional arrays can have one index per axis. These indices are given in a **tuple** separated by commas:

In [30]:
a = np.random.random((2, 3))
print a

[[ 0.30007595  0.17009519  0.92061579]
 [ 0.64273986  0.91573199  0.42044638]]


In [37]:
print a[0,1]                 # first row second column
print a[0,:]                 # first row
print a[:,0:2]               # all rows, first to second column
print a[-1]                  # last row, same as a[1,:]

0.170095187365
[ 0.30007595  0.17009519  0.92061579]
[[ 0.30007595  0.17009519]
 [ 0.64273986  0.91573199]]
[ 0.64273986  0.91573199  0.42044638]


In [38]:
for rows in a:
    print rows

[ 0.30007595  0.17009519  0.92061579]
[ 0.64273986  0.91573199  0.42044638]


In [41]:
for elem in a.flat:          # iterate over all elements
    print elem

0.300075951178
0.170095187365
0.920615790429
0.642739864806
0.915731986618
0.420446381414


Many functions are provided for shape changing

In [43]:
a = np.random.random((2, 3))
print a

[[ 0.34824388  0.73915642  0.76012123]
 [ 0.963917    0.57135937  0.41584273]]


In [54]:
print a.reshape((3, 2))
print np.resize(a, (3,2))

[[ 0.34824388  0.73915642]
 [ 0.76012123  0.963917  ]
 [ 0.57135937  0.41584273]]
[[ 0.34824388  0.73915642]
 [ 0.76012123  0.963917  ]
 [ 0.57135937  0.41584273]]


## Concatenate Numpy Arrays

In [8]:
x1 = np.full((1,3), 1, dtype=np.int64)
x2 = np.full((1,3), 2, dtype=np.int64)
x3 = np.full((1,3), 3, dtype=np.int64)
print x1
print x2
print x3

[[1 1 1]]
[[2 2 2]]
[[3 3 3]]


In [11]:
x_all = []
x_all.append(x1)
x_all.append(x2)
x_all.append(x3)
print type(x_all)
print x_all
print type(np.asarray(x_all))      # each row is a ndarray
print np.asarray(x_all)

<type 'list'>
[array([[1, 1, 1]]), array([[2, 2, 2]]), array([[3, 3, 3]])]
<type 'numpy.ndarray'>
[[[1 1 1]]

 [[2 2 2]]

 [[3 3 3]]]
